### ISSUE TITLE
Samba users not created on container deploy

### ISSUE THREAD

**Issue by dprevedello** [MekayelAnik/samba-server-alpine#1]
When the container is deployed, user creation fails. It seems that Samba users cannot be created unless the /etc/samba/smb.conf configuration file is present. Therefore, I recommend executing the user creation script constructUsers.sh after generating the smb.conf file using constructConf.sh within the smbd.sh script. I'd also like to take this opportunity to appreciate the outstanding work done with this Docker image.

**Comment by Hadatko** [comment]
Hello i had issue with this implementation until i mounted  samba folder so persistant folder: 
-v samba:/etc/samba

**Comment by MekayelAnik** [comment]
@dprevedello sorry for the late reply. Thanks for the compliment, I am glad you find this image helpful. BTW, the serial that is maintained in the smbd.sh is crucial is mandatory for it's proper and intended operations.

@Hadatko & @dprevedello please update the image to the latest of the date 08/09/2023. I hope the problem is resolved. Now no persistent storage should be needed for "/etc/samba/smb.conf".

Please let me know the update.

**Comment by MekayelAnik** [comment]
In my personal experience, I have found that this issue has been resolved.
